<testng-results>
  <reporter-output>
  </reporter-output>
  <suite name="TestAll">
    <groups>
    </groups>
    <test name="selenium">
      <class name="com.smart.dao.UserDaoTest">
        <test-method status="FAIL" signature="unitilsBeforeTestSetUp(java.lang.reflect.Method)" name="unitilsBeforeTestSetUp" is-config="true" duration-ms="0" started-at="2018-12-14T12:08:38Z" finished-at="2018-12-14T12:08:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.smart.dao.UserDaoTest.findUserByUserName()]]>
              </value>
            </param>
          </params>
          <exception class="org.unitils.core.UnitilsException">
            <message>
              <![CDATA[Error inserting test data from DbUnit dataset for method public void com.smart.dao.UserDaoTest.findUserByUserName()]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.unitils.core.UnitilsException: Error inserting test data from DbUnit dataset for method public void com.smart.dao.UserDaoTest.findUserByUserName()
	at org.unitils.dbunit.DbUnitModule.insertDataSet(DbUnitModule.java:190)
	at org.unitils.dbunit.DbUnitModule$DbUnitListener.beforeTestSetUp(DbUnitModule.java:791)
	at org.unitils.core.Unitils$UnitilsTestListener.beforeTestSetUp(Unitils.java:273)
	at org.unitils.UnitilsTestNG.unitilsBeforeTestSetUp(UnitilsTestNG.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:580)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:398)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:145)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:427)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:617)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:885)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:821)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:788)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:72)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:88)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.unitils.dbunit.DbUnitModule.getDefaultDbSupport(DbUnitModule.java:755)
	at org.unitils.dbunit.DbUnitModule.getDataSetFactory(DbUnitModule.java:725)
	at org.unitils.dbunit.DbUnitModule.getDataSetFactory(DbUnitModule.java:713)
	at org.unitils.dbunit.DbUnitModule.getDataSet(DbUnitModule.java:441)
	at org.unitils.dbunit.DbUnitModule.insertDataSet(DbUnitModule.java:261)
	at org.unitils.dbunit.DbUnitModule.insertDataSet(DbUnitModule.java:187)
	... 37 more
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="unitilsAfterTestTearDown(java.lang.reflect.Method)" name="unitilsAfterTestTearDown" is-config="true" duration-ms="33" started-at="2018-12-14T12:08:40Z" finished-at="2018-12-14T12:08:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.smart.dao.UserDaoTest.findUserByUserName()]]>
              </value>
            </param>
          </params>
        </test-method>
        <test-method status="SKIP" signature="findUserByUserName()" name="findUserByUserName" duration-ms="0" started-at="2018-12-14T12:08:40Z" finished-at="2018-12-14T12:08:40Z">
        </test-method>
        <test-method status="PASS" signature="unitilsBeforeClass()" name="unitilsBeforeClass" is-config="true" duration-ms="202" started-at="2018-12-14T12:08:37Z" finished-at="2018-12-14T12:08:38Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
